#domain_name: cd-ucla-test 
#project_name: californica
#env_name: us-east-2
ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}"



domain_name: util-ucla-test
project_name: fedora-solr-test
env_name: us-east-2
tomcat_applications:
  - app_name: fedora
    shut_port: 8008
    conn_port: 8081
    rproxy_path: fcrepo
