---
- hosts: localhost
  vars:
    host: cantaloupe-dev.curationexperts.com 

  roles:
    -  { role: dce_role_provision_ec2 }
    -  { role: dce_role_assign_eip, when: ec2_id is defined }
    -  { role: dce_role_route53_cm, when: ec2_id is defined }
#    -  { role: dce_role_provision_rds }
    -  { role: dce_role_end_play, when: ec2_exact_count == 0 }

- hosts: "{{ host }}"
  gather_facts: no
  become: yes
  user: ec2-user
  vars:
    host: "{{ hostvars['localhost']['host'] }}"
  var_files:
    - "{{ playbook_dir }}/host_vars/{{ host }}"

  roles:
    - { role: dce_role_wait_for_gatherfacts }
    - { role: dce_role_selinux_reboot }
    - { role: dce_role_wait_for_gatherfacts }
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_java, oracle_java_version: '1.8.0_191' }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_tomcat }
    - { role: uclalib_role_cantaloupe }

