---
- hosts: localhost
  vars:
   project_name: fedora-solr
   env_name: test

  roles:
    -  { role: dce_role_provision_ec2, ec2_exact_count: 1 }
    -  { role: dce_role_provision_rds }
#    -  { role: dce_role_end_play }

- hosts: ec2_group
  gather_facts: no
  become: yes
  user: ec2-user
  vars:
    project_name: fedora-solr
    env_name: test
    tomcat_applications:
      - app_name: fedora
        shut_port: 8008
        conn_port: 8081
        rproxy_path: fcrepo

  roles:
    - { role: dce_role_wait_for_gatherfacts }
    - { role: dce_role_selinux_reboot }
    - { role: dce_role_wait_for_gatherfacts }
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
  #  - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_samvera_basepackages }
    - { role: uclalib_role_pip }
    - { role: dce_role_rds_mysql }
    - { role: uclalib_role_java, oracle_java_version: '1.8.0_181' } 
    - { role: uclalib_role_apache } 
    - { role: uclalib_role_tomcat } 
    - { role: uclalib_role_fedora4, fedora_version: '4.7.5' }
    - { role: uclalib_role_solr7, solr_fqdn: "solr-ucla-test.testdce.com" }
