---
- name: Enable repos in aws
  ini_file:
    dest: /etc/yum.repos.d/redhat-rhui.repo
    section: "{{ item }}"
    option: enabled
    value: 1
  loop: 
    - rhui-REGION-rhel-server-releases
    - rhui-REGION-rhel-server-optional
    - rhui-REGION-rhel-server-supplementary
    - rhui-REGION-rhel-server-extras
