---

dependencies:
  - src: git+https://github.com/UCLALibrary/uclalib_role_uclalibrepo.git

galaxy_info:
  author: Stephen Gurnick - https://github.com/sgurnick
  description: Installs Ruby interpreter from uclalib repo
  company: UCLA Library
  license: reference LICENSE file
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
    - 7
