---
galaxy_info:
  author: Stephen Gurnick
  description: Ansible playbook to install the JRE/JDK.
  license: BSD 3-Clause
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 6
  categories:
  - system
dependencies: []
